### ISSUE TITLE
Issue with concurrent async write/read of the cache?

### ISSUE THREAD

**Issue by nhoizey** [KyleMit/eleventy-plugin-embed-tweet#1]
Hi @KyleMit, I want to use this plugin, but I have an issue.

It looks like the cache is sometimes broken because there are concurrent attemps to read and write the cache file. I sometimes get only fractions of tweets JSON in the file.

I think what might occur is that the file is currently written when another tweet process reads is, so the content is incomplete, and then written again like this.

But I'm really not good at Node.js async code. 😥

I solved the issue on my local fork with a synchronous `writeFileSync` call instead of the async `writeFile` you used in `addTweetToCache()`, but I'm really not sure it's a good idea.

Any advice?

Thanks

**Comment by KyleMit** [comment]
Thanks for the issue @nhoizey !  Certainly if `writeFileSync` fixes it, that seems to be the lowest hanging fruit.  I wonder if I can batch multiple read/writes together or call a sync lock while one is waiting to finish.  I'll look into it and get something in the works.  If you want to PR in your fork/branch, I'd accept that as a starter

**Comment by nhoizey** [comment]
Looks like it didn't fix the issue after all, I still have it, so I will keep looking before trying a PR… 😅

**Comment by nhoizey** [comment]
Couldn't find any fix yet.

However, I can at least report that:
- most of my builds work well
- when they do, I never have the same number of `Writing /…/_cache/tweets/tweets.json` lines in my shell
- I don't always have the same number of tweets in the cache either

I'm using the code from my PR #2 

I'll try to test with your code, without the PR.

**Comment by nhoizey** [comment]
I add that the transformation is done in HTML for all my tweets, the issue is only for the cache file.

**Comment by nhoizey** [comment]
@KyleMit I didn't have any issue for a few days (and a lot of builds) with PR #2, so I guess the issue was somewhere else… 😅

**Comment by nhoizey** [comment]
Really didn't have the issue for more than a month, with multiple builds every day.

**Comment by nhoizey** [comment]
I was wrong, I didn't get the issue because I didn't have new tweets in my content, so the cache was not written at all, being already there. 😅
