### ISSUE TITLE
Doesn't work with Eleventy 2.0.0 canary

### ISSUE THREAD

**Issue by brycewray** [KyleMit/eleventy-plugin-embed-tweet#17]
Just FYI, the current Eleventy 2.0.0 canary (with @zachleat's new server to substitute for BrowserSync) apparently has a problem with this plugin, since it crashed on launch with the following:

```bash
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eleventy_site@undefined
npm WARN Found: @11ty/eleventy@1.0.0
npm WARN node_modules/@11ty/eleventy
npm WARN   peer @11ty/eleventy@">=0.10.0-beta.1" from eleventy-plugin-embed-tweet@0.3.1
npm WARN   node_modules/eleventy-plugin-embed-tweet
npm WARN     dev eleventy-plugin-embed-tweet@"^0.3.1" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @11ty/eleventy@">=0.10.0-beta.1" from eleventy-plugin-embed-tweet@0.3.1
npm WARN node_modules/eleventy-plugin-embed-tweet
npm WARN   dev eleventy-plugin-embed-tweet@"^0.3.1" from the root project
```

**Comment by KyleMit** [comment]
Yeah, can repro with

```bash
npm i @11ty/eleventy@2.0.0-canary.1
npm i eleventy-plugin-embed-tweet
```

![image](https://user-images.githubusercontent.com/4307307/157532820-5bc6b3a2-00ec-416e-8e43-af9764884548.png)

**Comment by KyleMit** [comment]
I'll look to resolve this, but in the meantime, you can use `--force` like this:

```bash
npm install eleventy-plugin-embed-tweet --force
```

No reason the plugin shouldn't work with the latest version of 11ty, but gotta fix up so user's don't have a manual step

**Comment by brycewray** [comment]
> I'll look to resolve this, but in the meantime, you can use `--force` like this:
> 
> ```shell
> npm install eleventy-plugin-embed-tweet --force
> ```
> 
> No reason the plugin shouldn't work with the latest version of 11ty, but gotta fix up so user's don't have a manual step

Thanks. So just uninstall it and then reinstall it with that command?

**Comment by zachleat** [comment]
Cross linking this comment https://github.com/11ty/eleventy-dev-server/issues/5#issuecomment-1063409355
