### ISSUE TITLE
autoEmbed in Markdown problem?

### ISSUE THREAD

**Issue by huphtur** [KyleMit/eleventy-plugin-embed-tweet#7]
Not sure if bug or not, but URLs in my markdown do not automatically get linkified, so in order for [autoEmbed](https://github.com/KyleMit/eleventy-plugin-embed-tweet#autoembed) to work in Markdown, I have to make the URL a hyperlink. 

So instead of this:
`https://twitter.com/KyleMitBTV/status/1211079569245114371`

I have to do this:
`<https://twitter.com/KyleMitBTV/status/1211079569245114371>`

and then the plugin produces the publish.twitter.com embed. 

Is it possible to pass some settings to this embed? Theme, language, limit context, and Do Not Track (see [customization options](https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FKyleMitBTV%2Fstatus%2F1211079569245114371&widget=Tweet)).

**Comment by nhoizey** [comment]
@huphtur this is strange. Do you have a full Markdown content example to show, that doesn't work without the `<` and `>`?

Can you open a second issue for the settings part, so that it's easier to follow each topic? Thanks.

**Comment by huphtur** [comment]
@nhoizey check it out: https://github.com/huphtur/eleventy-base-blog/commit/c2ca282c196feebd92ed34683905b71b805d79dd

**Comment by nhoizey** [comment]
@huphtur ok, this is because you set `linkify: false` in Markdown, and the code looks for a link.

**Comment by huphtur** [comment]
Linkify was disabled to make sure [line 10](https://github.com/huphtur/eleventy-base-blog/commit/c2ca282c196feebd92ed34683905b71b805d79dd#diff-244efb6082e837a5a8cbbe0900d13fb6R10) doesn't turn into a link to demonstrate my example that dropping the Twitter URL in a markdown file does not work. Here's [a branch without markdownit options](https://github.com/huphtur/eleventy-base-blog/tree/sans-markdownit), same problem. Line 10 doesn't turn into embed.

Just tried adding a twitter URL on the eleventy-plugin-embed-tweet-demo package and same problem. So looks like I understood the docs wrong? 

Suggest changing:

> In the source Markdown, it only needs the tweet URL on one single line:
> 
> `https://twitter.com/KyleMitBTV/status/1211079569245114371`

to:

> In the source Markdown, it only needs the tweet URL on one single line:
> 
> `<https://twitter.com/KyleMitBTV/status/1211079569245114371>`

This way the plugin will look for a link and embed the tweet.

Let me know if that makes sense, and I'll fire of a PR for the doc change.

**Comment by nhoizey** [comment]
> Linkify was disabled to make sure [line 10](https://github.com/huphtur/eleventy-base-blog/commit/c2ca282c196feebd92ed34683905b71b805d79dd#diff-244efb6082e837a5a8cbbe0900d13fb6R10) doesn't turn into a link to demonstrate my example that dropping the Twitter URL in a markdown file does not work

The plugin currently works by identifying a link to a tweet with the tweet URL as the content. So yes, if you remove link automation, you need to make it a link yourself.

I'll make a PR to also look for a tweet URL in a paragraph, without any link.

**Comment by nhoizey** [comment]
@huphtur can you try #9 to see if it fixes your issue?

**Comment by huphtur** [comment]
Confirmed. Working 100%.
